# Generated by Django 2.1.8 on 2019-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prography',
            name='title',
            field=models.CharField(default='o', max_length=200),
            preserve_default=False,
        ),
    ]
